### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by encryptednonrandom** [kepoorhampond/irs#11]
~/irs$ irs -a "Ashley Wallbridge" -s "Goa (Extended Mix)"
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 9, in <module>
    load_entry_point('irs==6.2.2', 'console_scripts', 'irs')()
  File "/usr/local/lib/python3.5/dist-packages/irs-6.2.2-py3.5.egg/irs/cli.py", line 53, in main
    ripper.song(args.song, args.artist)
  File "/usr/local/lib/python3.5/dist-packages/irs-6.2.2-py3.5.egg/irs/ripper.py", line 293, in song
    song = data["name"]
KeyError: 'name'

**Comment by encryptednonrandom** [comment]
song input doesn't seem to like (). Also what about -t option for trackname such that trackname = "Ashley Wallbridge - Goa (Extended Mix)"

**Comment by encryptednonrandom** [comment]
https://www.youtube.com/watch?v=JUKPe_WDS4s

**Comment by kepoorhampond** [comment]
Well, I know what a `KeyError` is in Python, but I'll work on fixing it. I think it has to do with how it eliminates search results in Spotify. I'm thinking about migrating to a percentage based elimination system instead of a `true` or `false`.

**Comment by kepoorhampond** [comment]
Also, thanks for all the input into the repo! I appreciate it! And definitely feel free to open up some pull requests if you want to implement some features!

**Comment by kepoorhampond** [comment]
Fixed with #11, and I've added the functionality for easier parsing of parentheses!
