### ISSUE TITLE
add videourl to metadata

### ISSUE THREAD

**Issue by encryptednonrandom** [kepoorhampond/irs#12]
Feature request:
Can you add an option which can be set in the config file to include or not include (by default) the video_url to the comments/description field. It'd be nice to pass in --video-url option that adds the youtube video URL in the mp3 comments or description field. Doesn't have to be enabled by default but this would be a nice to have so mp3s can be tracked back to youtube source.

**Comment by kepoorhampond** [comment]
I actually had this in a previous version of the program, I'll re-implement it soon!

**Comment by kepoorhampond** [comment]
Done with 54e23c4!

**Comment by encryptednonrandom** [comment]
I verified this to be working with eyeD3. This commit adds the youtube url to Comment field as expected. 

1001.mp3	[ 5.71 MB ]
-------------------------------------------------------------------------------
Time: 04:07	MPEG1, Layer III	[ 192 kb/s @ 48000 Hz - Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: 1001		artist: Above & Beyond
album: 1001		year: None
boo
track: 1		genre: Trance (id 31)
disc: 1
Comment: [Description: ] [Lang: XXX]
URL: "https://youtube.com/watch?v=gbtKTaZU0HA"
Video Title: "Above & Beyond - 1001"

FRONT_COVER Image: [Size: 41908 bytes] [Type: image/png]
Description: cover
