### ISSUE TITLE
Accept "EOF" character as an alternative to "exit"

### ISSUE THREAD

**Issue by camilosampedro** [kepoorhampond/irs#17]
I think it could be a nice feature to accept an end of file character (e.g. `Ctrl + D`) to exit the IRC prompt as an alternative to the `exit` option. When you insert it, it shows this error:

```python
Traceback (most recent call last):
  File "/usr/bin/irs", line 11, in <module>
    load_entry_point('irs==6.3.0', 'console_scripts', 'irs')()
  File "/usr/lib/python3.6/site-packages/irs/cli.py", line 59, in main
    console(ripper)
  File "/usr/lib/python3.6/site-packages/irs/utils.py", line 253, in console
    choice = input("{0}irs{1}>{2} ".format(BBLUE, BGRAY, END))
EOFError
```

**Comment by kepoorhampond** [comment]
Is this the full `Traceback`? I'm not seeing the `Exception` name.

**Comment by camilosampedro** [comment]
Yes, it is the full `Traceback`. After `EOFError` it returns to the terminal prompt. Here it is a screenshot:

![captura de pantalla de 2017-03-20 21-38-28](https://cloud.githubusercontent.com/assets/8657866/24130274/95d1b708-0db5-11e7-8148-db0f3b87f6c6.png)

By the way, I'm in Linux x64, my distro is `Manjaro`, but I don't really think it could be related to the OS. 

Thank you for IRS!

**Comment by encryptednonrandom** [comment]
Where is version 6.3.0 avail? Source only shows version Version: 6.2.2

https://github.com/kepoorhampond/irs/blob/df86541d62406a065f63905219ec7295e1ff6fce/setup.py

**Comment by camilosampedro** [comment]
It came from its `pip` package: `irs`.

The way I installed was:

```bash
sudo pip install irs
```

**Comment by kepoorhampond** [comment]
Fixed! Sorry for the long response time, I've been on vacation away from wifi.

**Comment by camilosampedro** [comment]
Don't worry and thank you!
