### ISSUE TITLE
Configure directory of download

### ISSUE THREAD

**Issue by Rajesh-Veeranki** [kepoorhampond/irs#2]
How do I configure what parent directory the files should download to? Currently irs downloading to root directory (/) which is undesirable for my case.
![image](https://cloud.githubusercontent.com/assets/1542998/22333327/9c499918-e3fb-11e6-8675-ba2c4c1fddc3.png)

**Comment by kepoorhampond** [comment]
Did you edit the config file? Run `irs -C` to get the location of it.

**Comment by Rajesh-Veeranki** [comment]
I missed that part. Thanks!
BTW if you can make the default directory to be $HOME instead of / , people might find it bit easier

**Comment by kepoorhampond** [comment]
That's a good idea! I initially tried to use`~`, but it just made a tilde directory. I'll work on it!
