### ISSUE TITLE
Rename the file downloaded to match the source name instead of user input

### ISSUE THREAD

**Issue by Rajesh-Veeranki** [kepoorhampond/irs#3]
This is more of an enhancement. I searched for a song but it downloaded the same song in a different language. If we keep the name same as the source (youtube/spotify) name, it will help users identify what file they downloaded. Hope I made sense!

**Comment by kepoorhampond** [comment]
I'll add a config file option soon!

**Comment by kepoorhampond** [comment]
I've added it!

**Comment by Rajesh-Veeranki** [comment]
Awesome, thanks!
