### ISSUE TITLE
No token provided? 

### ISSUE THREAD

**Issue by malldancer** [kepoorhampond/irs#42]
I thought I had put my app tokens in the right file, but any time I try to dl something I get the following error? 

Here's one from me trying to find "Moontalk" by Laurel Halo. 

> Traceback (most recent call last):
>   File "/Users/caleb/anaconda/bin/irs", line 11, in <module>
>     load_entry_point('irs==6.7.6', 'console_scripts', 'irs')()
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/irs/cli.py", line 82, in main
>     console(ripper)
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/irs/utils.py", line 350, in console
>     ripper.song(song_name, artist_name)
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/irs/ripper.py", line 421, in song
>     data = self.parse_song_data(song, artist)
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/irs/ripper.py", line 382, in parse_song_data
>     album, track = find_album_and_track(song, artist, self.spotify)
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/irs/metadata.py", line 60, in find_album_and_track
>     tracks = spotify.search(q=song, type="track")["tracks"]["items"]
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/spotipy/client.py", line 339, in search
>     return self._get('search', q=q, limit=limit, offset=offset, type=type, market=market)
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/spotipy/client.py", line 146, in _get
>     return self._internal_call('GET', url, payload, kwargs)
>   File "/Users/caleb/anaconda/lib/python3.6/site-packages/spotipy/client.py", line 124, in _internal_call
>     headers=r.headers)
> spotipy.client.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/search?q=Moontalk&limit=10&offset=0&type=track:
>  No token provided

Have I put my tokens into the wrong files?

**Comment by Nythepegasus** [comment]
You can either put them in `/Users/caleb/.irs/_config.py` or you can provide them as environment variables. Ex.
```
export SPOTIFY_CLIENT_ID=client_id
export SPOTIFY_CLIENT_SECRET=client_secret
```
You should put that in your `~/.bash_profile` file. Either way works.
