### ISSUE TITLE
irs -l should show more info like view-count/upload-date/size 

### ISSUE THREAD

**Issue by Rajesh-Veeranki** [kepoorhampond/irs#6]
I think providing user with extra information like views, date, size helps them to have an informed decision.

**Comment by kepoorhampond** [comment]
That's a good idea! I've been thinking about reworking the `-l` flag anyways!

**Comment by kepoorhampond** [comment]
I've removed this flag with the newest version of the program because I've made it vastly more accurate. If there is still a need for it, I'll reopen it.
