### ISSUE TITLE
Better video sources

### ISSUE THREAD

**Issue by LvlAndFarm** [kepoorhampond/irs#8]
After looking at the source I saw that the program tries to pick lyric videos, which I understand, because of many reasons, but can you please try to add an experimental switch that tries to instead search using a string like this `song + " " + artist + " audio"` which I think may work better in some cases because some lyric videos have poor audio quality (try downloading the F.E.A.R. album by Papa Roach using the app and compare the quality with the original music videos). Maybe in the future I can come up with an algorithm that tries to pick the video with the best quality myself and file a pull request but right now I suggest you try the idea I told you above. And thanks for this cool program.

**Comment by kepoorhampond** [comment]
I've done it! Thanks for the feedback!
